// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDajn2XRgbhcZ52pW25UtoicJze4hGlfS4',
    appId: '1:7305023900:web:6e1cb8886f7d8f1f993859',
    messagingSenderId: '7305023900',
    projectId: 'loginapp-77e2b',
    authDomain: 'loginapp-77e2b.firebaseapp.com',
    storageBucket: 'loginapp-77e2b.appspot.com',
    measurementId: 'G-80D5ZEP4MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC86Mvc8sAokaPb7ByBnQRB6vM9L1V-41k',
    appId: '1:7305023900:android:2aa66145b8062f3a993859',
    messagingSenderId: '7305023900',
    projectId: 'loginapp-77e2b',
    storageBucket: 'loginapp-77e2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR7QYDXfczaW6thvBb_nC7ZaGblGHOx64',
    appId: '1:7305023900:ios:7b4e87a6c8705a22993859',
    messagingSenderId: '7305023900',
    projectId: 'loginapp-77e2b',
    storageBucket: 'loginapp-77e2b.appspot.com',
    iosBundleId: 'com.example.loginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAR7QYDXfczaW6thvBb_nC7ZaGblGHOx64',
    appId: '1:7305023900:ios:7bd7c87cf6697bfd993859',
    messagingSenderId: '7305023900',
    projectId: 'loginapp-77e2b',
    storageBucket: 'loginapp-77e2b.appspot.com',
    iosBundleId: 'com.example.loginPage.RunnerTests',
  );
}
